### ISSUE TITLE
Google CAPTCHA invalid key type

### ISSUE THREAD

**Issue by zono50** [MODSetter/SurfSense#10]
Hey there, so i went to recaptcha and got a site key and secret key, plugged them into the front end, and when i try to create a login, i'm getting the following.

![image](https://github.com/user-attachments/assets/61a4b386-02f3-4c24-8b60-cae9cca4225e)

I tried the V3 key and that didn't work, then tried a v2 key and that didn't work either, now i get unauthorized when i try to create an account 

![image](https://github.com/user-attachments/assets/5552af85-805e-40f2-b750-63a1791daf60)

also is it possible to bypass the google captchas, as they are seemingly cancer in digital form

**Comment by MODSetter** [comment]
v2 Keys should be used. Few ways to bypass captchas checks:

1. You can remove the check at https://github.com/MODSetter/SurfSense-Frontend/blob/53211d0b590ff5c7aaf721fbf0a39c21d7f0b823/components/logins/RegisterForm.tsx#L35

2. Or better just use swagger. FastAPI automatically generates Swagger UI. Go to your [BACKEND_URL]/docs/ (eg. http://127.0.0.1:8000/docs/ ) and you can directly register with register endpoint.
