### ISSUE TITLE
Frontend - Backend conection not working properly?

### ISSUE THREAD

**Issue by hnico21** [MODSetter/SurfSense#5]
I tried to set it up in docker container:

- I can view the frontend in browser. 
- I can register a user directly via api from browser
- **I cannot register a user via frontend or log in via frontend**  _-- This is the Problem_
- the extension is doing weird stuff

Also I registered an account on the demo-site a few days ago. Now I cant log in there either.

**Comment by Coqueiro** [comment]
Just someone interested in the project: since no Docker support has been officially provided yet, can you share your setup/configs? I believe it will be important for debugging.

**Comment by hnico21** [comment]
Hey, I sat down a few hours later an found the problem:
 In fronten/.env I set NEXT_PUBLIC_BACKEND_URL=http://backend:3000. So I pointed at the Docker container instead of the public domain. 
 
 I have no Idea how Github works 🙀 So I forked it an added my docker-compose.yml an Dockerfile to backend and frontend.

**Comment by MODSetter** [comment]
> * the extension is doing weird stuff

Do let me know what were the issues

> Also I registered an account on the demo-site a few days ago. Now I cant log in there either.

Main site Backend is offline I will deal with it if I want to release some managed version.
